table D_job
	lineageTag: 0b06fe2b-5470-4a78-a4ed-18b09df49ca4

	column job_desc
		dataType: string
		lineageTag: 7d2ddd17-2416-4bfe-b53d-10f55b3f8fdf
		summarizeBy: none
		sourceColumn: job_desc

		annotation SummarizationSetBy = Automatic

	column job_group
		dataType: string
		lineageTag: 46de6890-fd14-4dab-88e9-fc79d4222681
		summarizeBy: none
		sourceColumn: job_group

		annotation SummarizationSetBy = Automatic

	column job_key
		dataType: int64
		formatString: 0
		lineageTag: cb3e47bb-b87c-451e-99e9-63b843a65eec
		summarizeBy: none
		sourceColumn: job_key

		annotation SummarizationSetBy = Automatic

	partition D_job = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Thepilli/public_service/refs/heads/main/PBI/D_job.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_key", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = DIMs

