table D_party
	lineageTag: eb09d9b7-5551-4831-92c4-c5dcd5ae6986

	/// This measure is the sum of column 'D_party'[party_long]
	measure 'SELECTEDVALUE of party_long' = SELECTEDVALUE('D_party'[party_long])
		lineageTag: d0bd4279-9062-4fd1-a6aa-31e2f35c05ab

	column party_key
		dataType: int64
		formatString: 0
		lineageTag: 272ee5ee-4be5-4f2d-8e41-ffcf36c2f778
		summarizeBy: none
		sourceColumn: party_key

		annotation SummarizationSetBy = Automatic

	column party_short
		dataType: string
		lineageTag: 976dcf82-d274-4cd2-b232-e1dc8fa5b6c3
		summarizeBy: none
		sourceColumn: party_short

		annotation SummarizationSetBy = Automatic

	column party_long
		dataType: string
		isHidden
		lineageTag: 81511670-ed23-437e-a99b-ef4cf5196c05
		summarizeBy: none
		sourceColumn: party_long

		annotation SummarizationSetBy = Automatic

	partition D_party = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jirip\Documents\Developer\python\Public Service\PBI\D_party.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"party_key", Int64.Type}, {"party_short", type text}, {"party_long", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = DIMs

