table F_dary_po
	lineageTag: 68b1420b-4163-44c5-9143-c9a2af7e6d2f

	column party_key
		dataType: int64
		formatString: 0
		lineageTag: 92b0b8e7-9514-4d09-8c6a-42cb3505585d
		summarizeBy: none
		sourceColumn: party_key

		annotation SummarizationSetBy = Automatic

	column date_donation
		dataType: dateTime
		formatString: Long Date
		lineageTag: 80016f84-c147-41bc-8dd6-1c13b17e2de2
		summarizeBy: none
		sourceColumn: date_donation

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column amount
		dataType: double
		lineageTag: 47fc8680-f8e9-4a40-ab46-13f3607e4b7c
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column companyId
		dataType: string
		lineageTag: 82a346c2-1d27-4646-8b28-c3c2c0b56dcf
		summarizeBy: none
		sourceColumn: companyId

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 6e53108b-394f-4ede-af26-ab65677e2a3f
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: da02e59a-f8e9-488f-9857-f2befa205bc9
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition F_dary_po = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jirip\Documents\Developer\python\Public Service\CURATED\penizepo.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"ic", "party_key"}, {"date", "date_donation"}, {"money", "amount"}}),
				    #"Inserted Date" = Table.AddColumn(#"Renamed Columns", "Date", each Date.From([year]), type date),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Date",{"addrStreet", "addrCity", "addrZip", "year"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"party_key", Int64.Type}, {"date_donation", type date}, {"amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

