table F_dluhy
	lineageTag: ba29b9e0-02f9-4692-8179-5530dd6dc970

	column ic
		dataType: int64
		formatString: 0
		lineageTag: c8bdc65f-ad3e-4aa1-9897-9bf63487eeaa
		summarizeBy: none
		sourceColumn: ic

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 25532950-c7ab-4bb3-bb69-85f8d7291d52
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column companyId
		dataType: int64
		formatString: 0
		lineageTag: 49ef22bb-a4fe-4529-9abb-2120efc9da41
		summarizeBy: count
		sourceColumn: companyId

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: 37688d89-e221-484f-853a-01b660e13b85
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column share
		dataType: int64
		formatString: 0
		lineageTag: c83701fd-6eca-4503-bfde-3bdb027877e5
		summarizeBy: sum
		sourceColumn: share

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 590e3265-afea-4156-af23-ffcdf5eaa975
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition F_dluhy = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jirip\Documents\Developer\python\Public Service\CURATED\podil.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Inserted Date" = Table.AddColumn(#"Promoted Headers", "Date", each Date.From(Text.From([year], "en-US")), type date),
				    #"Changed Type" = Table.TransformColumnTypes(#"Inserted Date",{{"year", Int64.Type}, {"ic", Int64.Type}, {"name", type text}, {"companyId", Int64.Type}, {"address", type text}, {"share", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"year"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

