table F_zamestnanci
	lineageTag: 11be73bb-ed60-442c-9391-23a7d7746bc8

	column date_year
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 4a0b7872-8977-4466-a075-844a29565b0d
		summarizeBy: none
		sourceColumn: date_year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column party_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b90711d8-2d9e-4806-bf99-d75b4600eacb
		summarizeBy: none
		sourceColumn: party_key

		annotation SummarizationSetBy = Automatic

	column job_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e73bd3d6-599a-47c4-b7bc-79a1cd4a9f4e
		summarizeBy: none
		sourceColumn: job_key

		annotation SummarizationSetBy = Automatic

	column job_count
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 63642e59-96dc-44fa-afaf-82cd36e5f46f
		summarizeBy: sum
		sourceColumn: job_count

		annotation SummarizationSetBy = Automatic

	partition F_zamestnanci = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jirip\Documents\Developer\python\Public Service\PBI\F_zamestnanci.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_year", type date}, {"party_key", Int64.Type}, {"job_key", Int64.Type}, {"job_count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = FACTs

